import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { renderSchema, type ColumnInfo, type SchemaInfo } from "./schema-snapshot.ts";

function column(overrides: Partial<ColumnInfo> & { name: string; type: string }): ColumnInfo {
  return {
    notNull: false,
    defaultExpr: null,
    identity: "",
    generated: "",
    ownsSequence: false,
    ...overrides,
  };
}

function schema(overrides: Partial<SchemaInfo> = {}): SchemaInfo {
  return {
    appliedMigrations: [],
    functions: [],
    tables: [],
    foreignKeys: [],
    indexes: [],
    triggers: [],
    ...overrides,
  };
}

describe("renderSchema", () => {
  it("列の型・NOT NULL・DEFAULT をそのまま並べる", () => {
    const sql = renderSchema(
      schema({
        tables: [
          {
            name: "users",
            columns: [
              column({ name: "email", type: "text", notNull: true }),
              column({ name: "created_at", type: "timestamptz", notNull: true, defaultExpr: "now()" }),
              column({ name: "note", type: "text" }),
            ],
            constraints: [],
          },
        ],
      }),
    );

    assert.match(sql, /CREATE TABLE users \(/);
    assert.match(sql, /email\s+text\s+NOT NULL/);
    assert.match(sql, /created_at\s+timestamptz\s+NOT NULL DEFAULT now\(\)/);
    // 修飾が無い列には余計な語を足さない
    assert.match(sql, /note\s+text\n/);
  });

  it("シーケンスを持つ整数列は serial に畳み、nextval は出さない", () => {
    const sql = renderSchema(
      schema({
        tables: [
          {
            name: "horses",
            columns: [
              column({
                name: "id",
                type: "bigint",
                notNull: true,
                defaultExpr: "nextval('horses_id_seq'::regclass)",
                ownsSequence: true,
              }),
            ],
            constraints: [],
          },
        ],
      }),
    );

    assert.match(sql, /id\s+bigserial\s+NOT NULL/);
    assert.doesNotMatch(sql, /nextval/);
  });

  it("シーケンスを持たない整数列は畳まない", () => {
    const sql = renderSchema(
      schema({
        tables: [
          {
            name: "races",
            columns: [column({ name: "distance", type: "integer", notNull: true })],
            constraints: [],
          },
        ],
      }),
    );

    assert.match(sql, /distance\s+integer\s+NOT NULL/);
    assert.doesNotMatch(sql, /serial/);
  });

  it("identity 列と生成列を型の後ろに書く", () => {
    const sql = renderSchema(
      schema({
        tables: [
          {
            name: "t",
            columns: [
              column({ name: "a", type: "bigint", notNull: true, identity: "d", defaultExpr: null }),
              column({ name: "b", type: "bigint", notNull: true, identity: "a" }),
              column({ name: "c", type: "text", generated: "s", defaultExpr: "upper(a)" }),
            ],
            constraints: [],
          },
        ],
      }),
    );

    assert.match(sql, /a\s+bigint\s+NOT NULL GENERATED BY DEFAULT AS IDENTITY/);
    assert.match(sql, /b\s+bigint\s+NOT NULL GENERATED ALWAYS AS IDENTITY/);
    assert.match(sql, /c\s+text\s+GENERATED ALWAYS AS \(upper\(a\)\) STORED/);
    // 生成列の式は DEFAULT としては出さない
    assert.doesNotMatch(sql, /DEFAULT upper/);
  });

  it("テーブル内の制約は 主キー → 一意 → CHECK の順に並べる", () => {
    const sql = renderSchema(
      schema({
        tables: [
          {
            name: "users",
            columns: [column({ name: "id", type: "bigint", notNull: true })],
            constraints: [
              { name: "users_level_check", type: "c", definition: "CHECK (access_level = 'owner')" },
              { name: "users_email_key", type: "u", definition: "UNIQUE (email)" },
              { name: "users_pkey", type: "p", definition: "PRIMARY KEY (id)" },
            ],
          },
        ],
      }),
    );

    const order = ["users_pkey", "users_email_key", "users_level_check"].map((name) =>
      sql.indexOf(name),
    );

    assert.ok(order.every((position) => position !== -1));
    assert.deepEqual([...order].sort((a, b) => a - b), order);
  });

  it("外部キーはテーブル定義の外に、ALTER TABLE でまとめて出す", () => {
    const sql = renderSchema(
      schema({
        tables: [
          {
            name: "entries",
            columns: [column({ name: "horse_id", type: "bigint", notNull: true })],
            constraints: [],
          },
        ],
        foreignKeys: [
          {
            table: "entries",
            constraint: {
              name: "entries_horse_id_fkey",
              type: "f",
              definition: "FOREIGN KEY (horse_id) REFERENCES horses(id) ON DELETE RESTRICT",
            },
          },
        ],
      }),
    );

    assert.match(
      sql,
      /ALTER TABLE entries ADD CONSTRAINT entries_horse_id_fkey FOREIGN KEY \(horse_id\) REFERENCES horses\(id\) ON DELETE RESTRICT;/,
    );
    // CREATE TABLE の中に混ざらない
    const createTable = sql.slice(sql.indexOf("CREATE TABLE entries"), sql.indexOf(");"));
    assert.doesNotMatch(createTable, /FOREIGN KEY/);
  });

  it("適用済みマイグレーションを頭に書く", () => {
    const sql = renderSchema(schema({ appliedMigrations: ["0001_initial.sql", "0002_add_x.sql"] }));

    assert.match(sql, /-- {3}0001_initial\.sql/);
    assert.match(sql, /-- {3}0002_add_x\.sql/);
  });

  it("マイグレーションが1本も無ければ「なし」と書く", () => {
    assert.match(renderSchema(schema()), /適用済みマイグレーション: なし/);
  });

  it("中身が無い区分の見出しは出さない", () => {
    const sql = renderSchema(schema({ indexes: [], triggers: [] }));

    assert.doesNotMatch(sql, /インデックス/);
    assert.doesNotMatch(sql, /トリガー/);
    assert.doesNotMatch(sql, /外部キー/);
  });

  it("関数・インデックス・トリガーは定義に ; を付けて出す", () => {
    const sql = renderSchema(
      schema({
        functions: ["CREATE OR REPLACE FUNCTION public.set_updated_at()\n RETURNS trigger\n..."],
        indexes: ["CREATE INDEX horses_name_idx ON public.horses USING btree (name)"],
        triggers: [
          "CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION set_updated_at()",
        ],
      }),
    );

    assert.match(sql, /RETURNS trigger\n\.\.\.;/);
    assert.match(sql, /CREATE INDEX horses_name_idx ON public\.horses USING btree \(name\);/);
    assert.match(sql, /EXECUTE FUNCTION set_updated_at\(\);/);
  });

  it("末尾は改行1つで終わる", () => {
    const sql = renderSchema(
      schema({
        tables: [
          { name: "t", columns: [column({ name: "id", type: "bigint" })], constraints: [] },
        ],
      }),
    );

    assert.ok(sql.endsWith(");\n"));
  });
});
